config/routes.rb
HotHackers::Application.routes.draw do
  root :to => "matches#new"
  resources :matches
  resources :hackers
end

app/models/hacker.rb
class Hacker < ActiveRecord::Base
  attr_accessible :username

  before_validation :canonalize_username

  validates :username, :presence => true,
                       :uniqueness => true

  validate :username_is_github_user, :on => :create

  protected

  def canonalize_username
    self.username = self.username.downcase.strip
  end

  GITHUB_BASE_URL = 'http://github.com/api/v2/yaml/user/show/'

  def username_is_github_user
    res = HTTParty.get(GITHUB_BASE_URL + self.username) rescue nil

    if res && res.code == 200
      hacker_data = res['user']
      self.gravatar_id = hacker_data['gravatar_id']
    else
      errors.add(:username, :invalid)
    end
  end
end

app/models/match.rb
require 'digest/sha1'

class Match
  K_FACTOR = 32
  DESVSTD  = 150

  attr_accessor :left_hacker, :right_hacker, :signature, :token

  def initialize
    num_hackers = Hacker.count
    left_offset = right_offset = rand(num_hackers)
    self.left_hacker = Hacker.first :offset => left_offset

    # Select a second hacker with a comparable level to the first
    num_hackers, limit = 0, 0
    while num_hackers == 0
      limit += DESVSTD
      num_hackers = Hacker.where('ranking > ? and ranking < ?',
                                self.left_hacker.ranking - limit,
                                self.left_hacker.ranking + limit).count
    end
    right_offset = rand(num_hackers) until left_offset != right_offset
    self.right_hacker = Hacker.first :offset => right_offset

    self.token = SecureRandom.hex(10)
    self.signature = self.class.calculate_signature(self.left_hacker.id,
                                                    self.right_hacker.id,
                                                    self.token)
  end

  def self.calculate_rankings!(match, match_token)
    if match[:signature] != self.calculate_signature(match[:left_hacker_id],
                                                     match[:right_hacker_id],
                                                     match_token)
      raise InvalidRequestError
    end

    left_hacker = Hacker.find match[:left_hacker_id]
    right_hacker = Hacker.find match[:right_hacker_id]
    winner = match[:winner].to_i

    q_left = 10**(left_hacker.ranking / 400.0)
    q_right = 10**(right_hacker.ranking / 400.0)
    denominator = q_left + q_right
    e_left = q_left / denominator
    e_right = q_right / denominator

    s_left, s_right = left_hacker.id == winner ? [1, 0] : [0, 1]
    Hacker.transaction do
      Hacker.update_all(['ranking = ranking + ?', (K_FACTOR * (s_left - e_left)).to_i],
                        :id => left_hacker.id)
      Hacker.update_all(['ranking = ranking + ?', (K_FACTOR * (s_right - e_right)).to_i],
                        :id => right_hacker.id)
    end

    left_hacker.id == winner ? left_hacker : right_hacker
  end

  def self.calculate_signature(left_id, right_id, match_token)
    Digest::SHA1.hexdigest("#{match_token}---#{left_id}---#{right_id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from InvalidRequestError do |exception|
    redirect_to root_url, :flash => { :error => "No cheating allowed (or double clicks)" }
  end
end

app/controllers/hackers_controller.rb
class HackersController < ApplicationController
  def index
    @hackers = Hacker.order('ranking DESC').paginate(:page => params[:page] || 1)
  end

  def new
    @hacker = Hacker.new
  end

  def create
    @hacker = Hacker.new(params[:hacker])

    if @hacker.save
      redirect_to root_url, :notice => 'Hacker created!'
    else
      render :new
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def new
    @match = Match.new
    session[:match_token] = @match.token
  end

  def create
    match_token = session[:match_token]
    session[:match_token] = nil
    winner = Match.calculate_rankings! params[:match], match_token
    flash[:notice] = "#{winner.username} wins!"
    redirect_to new_match_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  GRAVATAR_BASE_URL = 'http://www.gravatar.com/avatar'
  def gravatar_url(gravatar_id, options)
    options = options.reverse_merge('d' => 'mm')
    query_string = options.to_query
    "#{GRAVATAR_BASE_URL}/#{gravatar_id}?#{query_string}"
  end

  GITHUB_BASE_URL = 'https://github.com'
  def github_url(github_username)
    "#{GITHUB_BASE_URL}/#{github_username}"
  end
end

app/helpers/hackers_helper.rb
module HackersHelper
  def class_for_hacker_row(position)
    case position
    when 1 then "first"
    when 2 then "second"
    when 3 then "third"
    else        ""
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/hackers/_hacker.html.erb
<tr class="<%= class_for_hacker_row(offset + hacker_counter) %>">
  <td class="position-col"><%= offset + hacker_counter %></td>
  <td>
    <img class="gravatar" src="<%= gravatar_url(hacker.gravatar_id, 's' => 40)%>">
    <%= link_to hacker.username, github_url(hacker.username) %>
  </td>
  <td class="ranking-col"><%= hacker.ranking %></td>
</tr>

app/views/hackers/index.html.erb
<h1>Who’s the hottest hacker of them all?</h1>
<table class="hackers-ranking">
  <thead>
    <tr>
      <th>Position</th>
      <th>Username</th>
      <th>Ranking</th>
    </tr>
  </thead>
  <tbody>
    <%= render @hackers, :offset => @hackers.offset + 1 %>
  </tbody>
</table>

<%= will_paginate @hackers, :page_links => false %>

app/views/hackers/new.html.erb
<h1>Introduce your GitHub account name</h1>

<% form_for @hacker do |f| -%>
  <% f.object.errors.full_messages.each do |e| %>
    <p><%= e %></p>
  <% end %>
  <%= f.text_field :username %>
  <button class="fancy" value="submit" type="submit">Create</button>
<% end -%>

app/views/layouts/application.html.haml
!!! 5
%html{ 'lang' => 'en' }
  %head
    = render 'shared/head_contents'
    = yield :head
  %body.hot-hackers.mainpage
    = render 'shared/header'
    #container
      #wrapper
        = render 'shared/flash'
        #main
          = yield
    #footer
      .inner
        = render 'shared/footer'
    =yield :body_end

app/views/matches/new.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'jquery.template' %>
  <%= javascript_include_tag 'github-badge-launcher' %>
<% end %>

<%= form_tag matches_url do -%>
  <%= hidden_field_tag 'match[signature]', @match.signature %>
  <%= hidden_field_tag 'match[left_hacker_id]', @match.left_hacker.id %>
  <%= hidden_field_tag 'match[right_hacker_id]', @match.right_hacker.id %>

  <div class="left-hacker">
    <img class="gravatar" src="<%= gravatar_url(@match.left_hacker.gravatar_id, 's' => 128)%>">
    <button class="fancy" name="match[winner]" value="<%= @match.left_hacker.id %>">Vote for <%= @match.left_hacker.username %></button>
    <div class="github-badge" data-username="<%= @match.left_hacker.username %>"></div>
  </div>

  <div class="right-hacker">
    <img class="gravatar" src="<%= gravatar_url(@match.right_hacker.gravatar_id, 's' => 128)%>">
    <button class="fancy" name="match[winner]" value="<%= @match.right_hacker.id %>">Vote for <%= @match.right_hacker.username %></button>
    <div class="github-badge" data-username="<%= @match.right_hacker.username %>"></div>  
  </div>
<% end -%>

app/views/shared/_flash.html.haml
- if self.flash && self.flash.size > 0
  .flash
    - self.flash.each do |type, message|
      %div{ :class => "message #{type}" }
        %p= message

app/views/shared/_footer.html.haml
#links-col
  %h3 Options
  %ul
    %li=link_to 'New match', new_match_url, :title => 'New match'
    %li=link_to 'Add a new hacker', new_hacker_url, :title => 'Add hacker'
    %li=link_to 'See the hacker ranking', hackers_url, :title => 'Hackers ranking'
#copyright Copyright 2010 Daniel &amp; Jorge

app/views/shared/_head_contents.html.haml
%meta{ 'http-equiv' => 'Content-Type', 'content' => 'text/html; charset=utf-8' }/
%title Hot Hackers
= stylesheet_link_tag 'compiled/screen.css', 'badge.css', :media => 'screen, projection'
= stylesheet_link_tag 'compiled/print.css', :media => 'print'
/[if lt IE 8]
  = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
/[if lt IE 7]
  = stylesheet_link_tag 'compiled/ie6.css', :media => 'screen, projection'
= javascript_include_tag :defaults
= csrf_meta_tag

app/views/shared/_header.html.haml
#header
  .inner
    %h1
      %a{ 'href' => '/' }
        %span HotHackers